### PR TITLE
Add visualizer for audio input

### PR DESCRIPTION
**Pull request by stevenpetryk**
screen shot 2017-04-17 at 2 52 57 pm

It turns red when you're recording:

screen shot 2017-04-17 at 2 54 12 pm

### CODE REVIEW

**Comment by maxcell** [comment]
Suggestion: could it just apply the red that is on the color pallete?

**Comment by stevenpetryk** [comment]
It becomes the same red as the record button red. If we wanna change this to drawing red, we should change all the recording buttons too.

**Comment by maxcell** [comment]
Fair :) no worries!

**Comment by maxcell** [comment]
It should be enough feedback for a user so that makes sense :)

**Review by maxcell — APPROVED** [review]

**Review by maxcell — APPROVED** [review]

**Pull request merged**
